const mongoose = require('mongoose');
const captainSchema = mongoose.Schema({
    fullname:{
        firstname:{
            type:String,
            required:true,
            minlength:[3,"Firstname must contain atleast 3 characters!"]
        },
        lastname:{
            type:String
        }
    },
    phone:{
        type:Number,
        required:true
    },
    email:{
        type:String,
        required:true,
        lowercase:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
        select:false
    },
    socketid:{
        type:String
    },
    status:{
        type:String,
        enum:["active","inactive"],
        default:"inactive"
    },
    image:{
        type:String,
        default:''
    },
    vehicle:{
        color:{
            type:String,
            required:true
        },
        plate:{
            type:String,
            required:true
        },
        capacity:{
            type:Number,
            default:1,
        },
        vehicletype:{
            type:String,
            enum:["auto","car","bike"],
            required:true
        }
    },
    location:{
        lng:{
            type:Number
        },
        ltd:{
            type:Number
        }
    }
});
module.exports = mongoose.model("Captain",captainSchema)